# Bibliotecas

In [ ]:
!pip install -U pip

Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (24.1.2)
Collecting pip
  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 31.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-24.2

In [ ]:
!pip install ktrain
!pip install tensorflow
!pip install tf_keras

Collecting ktrain
  Downloading ktrain-0.41.4.tar.gz (25.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.3/25.3 MB 40.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from ktrain) (1.5.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from ktrain) (3.7.1)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from ktrain) (2.2.2)
Requirement already satisfied: fastprogress>=0.1.21 in /usr/local/lib/python3.10/dist-packages (from ktrain) (1.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from ktrain) (2.32.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from ktrain) (1.4.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from ktrain) (24.1)
Collecting langdetect (from ktrain)
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 29.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: jieba in /usr/local/lib/python3.10/dist-packages (from ktrain) (0.42.1)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.10/dist-packages (from ktrain) (3.4.0)
Requirement already satisfied: chardet in /usr/local/lib/python3.10/dist-packages (from ktrain) (5.2.0)
Collecting syntok>1.3.3 (from ktrain)
  Downloading syntok-1.4.4-py3-none-any.whl.metadata (10 kB)
Collecting tika (from ktrain)
  Downloading tika-2.6.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (from ktrain) (4.44.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from ktrain) (0.2.0)
Collecting keras_bert>=0.86.0 (from ktrain)
  Downloading keras-bert-0.89.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting whoosh (from ktrain)
  Downloading Whoosh-2.7.4-py2.py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from keras_bert>=0.86.0->ktrain) (1.26.4)
Collecting keras-transformer==0.40.0 (from keras_bert>=0.86.0->ktrain)
  Downloading keras-transformer-0.40.0.tar.gz (9.7 kB)
  Preparing metadata (setup.py) ... done
Collecting keras-pos-embd==0.13.0 (from keras-transformer==0.40.0->keras_bert>=0.86.0->ktrain)
  Downloading keras-pos-embd-0.13.0.tar.gz (5.6 kB)
  Preparing metadata (setup.py) ... done
Collecting keras-multi-head==0.29.0 (from keras-transformer==0.40.0->keras_bert>=0.86.0->ktrain)
  Downloading keras-multi-head-0.29.0.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting keras-layer-normalization==0.16.0 (from keras-transformer==0.40.0->keras_bert>=0.86.0->ktrain)
  Downloading keras-layer-normalization-0.16.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... done
Collecting keras-position-wise-feed-forward==0.8.0 (from keras-transformer==0.40.0->keras_bert>=0.86.0->ktrain)
  Downloading keras-position-wise-feed-forward-0.8.0.tar.gz (4.1 kB)
  Preparing metadata (setup.py) ... done
Collecting keras-embed-sim==0.10.0 (from keras-transformer==0.40.0->keras_bert>=0.86.0->ktrain)
  Downloading keras-embed-sim-0.10.0.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
Collecting keras-self-attention==0.51.0 (from keras-multi-head==0.29.0->keras-transformer==0.40.0->keras_bert>=0.86.0->ktrain)
  Downloading keras-self-attention-0.51.0.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->ktrain) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->ktrain) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->ktrain) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->ktrain) (1.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->ktrain) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->ktrain) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->ktrain) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->ktrain) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.1->ktrain) (2024.2)
Requirement already satisfied: regex>2016 in /usr/local/lib/python3.10/dist-packages (from syntok>1.3.3->ktrain) (2024.9.11)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from langdetect->ktrain) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->ktrain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->ktrain) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->ktrain) (2024.8.30)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->ktrain) (1.13.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->ktrain) (3.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tika->ktrain) (71.0.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers->ktrain) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers->ktrain) (0.24.7)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers->ktrain) (6.0.2)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers->ktrain) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers->ktrain) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers->ktrain) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers->ktrain) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers->ktrain) (4.12.2)
Downloading syntok-1.4.4-py3-none-any.whl (24 kB)
Downloading Whoosh-2.7.4-py2.py3-none-any.whl (468 kB)
Building wheels for collected packages: ktrain, keras_bert, keras-transformer, keras-embed-sim, keras-layer-normalization, keras-multi-head, keras-pos-embd, keras-position-wise-feed-forward, keras-self-attention, langdetect, tika
  Building wheel for ktrain (setup.py) ... done
  Created wheel for ktrain: filename=ktrain-0.41.4-py3-none-any.whl size=25316932 sha256=6ca8f1f1aba244551dac257cdf0372b00777025b0bbd17ff41b1747fb38e6280
  Stored in directory: /root/.cache/pip/wheels/fa/6a/9c/8a873b38bbd8bc207d33c64726bd18f7ef85f8e70dc3ac2e4b
  Building wheel for keras_bert (setup.py) ... done
  Created wheel for keras_bert: filename=keras_bert-0.89.0-py3-none-any.whl size=33500 sha256=065bbd0c6e8513ac5be965d6dd4a6b3897eb386b5da2d831e26a52764ec49bd1
  Stored in directory: /root/.cache/pip/wheels/89/0c/04/646b6fdf6375911b42c8d540a8a3fda8d5d77634e5dcbe7b26
  Building wheel for keras-transformer (setup.py) ... done
  Created wheel for keras-transformer: filename=keras_transformer-0.40.0-py3-none-any.whl size=12286 sha256=2d40047efb80ef7bf480b076e34b9eb6f5694ce840bb472ce2518c8e4b140f2a
  Stored in directory: /root/.cache/pip/wheels/f2/cb/22/75a0ad376129177f7c95c0d91331a18f5368fd657f4035ba7c
  Building wheel for keras-embed-sim (setup.py) ... done
  Created wheel for keras-embed-sim: filename=keras_embed_sim-0.10.0-py3-none-any.whl size=3944 sha256=ba4f5b5fac93cc779c81f66542cebd346bdd2ee77a1ac313e36e0b39a1133b59
  Stored in directory: /root/.cache/pip/wheels/82/32/c7/fd35d0d1b840a6c7cbd4343f808d10d0f7b87d271a4dbe796f
  Building wheel for keras-layer-normalization (setup.py) ... done
  Created wheel for keras-layer-normalization: filename=keras_layer_normalization-0.16.0-py3-none-any.whl size=4654 sha256=e19475d5000f6d66db23c55d9bda8106eaf625f4d1204a347f897cb1696b7e0b
  Stored in directory: /root/.cache/pip/wheels/ed/3a/4b/21db23c0cc56c4b219616e181f258eb7c57d36cc5d056fae9a
  Building wheel for keras-multi-head (setup.py) ... done
  Created wheel for keras-multi-head: filename=keras_multi_head-0.29.0-py3-none-any.whl size=14975 sha256=fb3cc9f5dc44511c59ea720ba7a78bf7836b5d712bb4342b8b44d4f4cbcbb7a7
  Stored in directory: /root/.cache/pip/wheels/cb/23/4b/06d7ae21714f70fcc25b48f972cc8e5e7f4b6b764a038b509d
  Building wheel for keras-pos-embd (setup.py) ... done
  Created wheel for keras-pos-embd: filename=keras_pos_embd-0.13.0-py3-none-any.whl size=6946 sha256=a2c38f0ec5f6bc001722bfeb297430d6b45baa2dae5f995b6e54c8f028e38d37
  Stored in directory: /root/.cache/pip/wheels/78/07/1b/b1ca47b6ac338554b75c8f52c54e6a2bfbe1b07d79579979a4
  Building wheel for keras-position-wise-feed-forward (setup.py) ... done
  Created wheel for keras-position-wise-feed-forward: filename=keras_position_wise_feed_forward-0.8.0-py3-none-any.whl size=4971 sha256=9af5d6d4394198b02b729fc6415245c83315d27e4a135ba57962ac70486ffb71
  Stored in directory: /root/.cache/pip/wheels/c1/6a/04/d1706a53b23b2cb5f9a0a76269bf87925daa1bca09eac01b21
  Building wheel for keras-self-attention (setup.py) ... done
  Created wheel for keras-self-attention: filename=keras_self_attention-0.51.0-py3-none-any.whl size=18894 sha256=4b423fed2ad5080808e5b02780d6c879fd1ca3782defdee52378d3d5cc2df5c8
  Stored in directory: /root/.cache/pip/wheels/b8/f7/24/607b483144fb9c47b4ba2c5fba6b68e54aeee2d5bf6c05302e
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993221 sha256=f55492b1bc7351298f12a3dbd7e9845043b1d7bd52933f16e2b8006c49b2caa9
  Stored in directory: /root/.cache/pip/wheels/95/03/7d/59ea870c70ce4e5a370638b5462a7711ab78fba2f655d05106
  Building wheel for tika (setup.py) ... done
  Created wheel for tika: filename=tika-2.6.0-py3-none-any.whl size=32623 sha256=202cc1a560ea65e4e8da5592dd0e6c59abc21c9f6afde2c23498dc8e2ec943ca
  Stored in directory: /root/.cache/pip/wheels/5f/71/c7/b757709531121b1700cffda5b6b0d4aad095fb507ec84316d0
Successfully built ktrain keras_bert keras-transformer keras-embed-sim keras-layer-normalization keras-multi-head keras-pos-embd keras-position-wise-feed-forward keras-self-attention langdetect tika
Installing collected packages: whoosh, syntok, langdetect, keras-self-attention, keras-position-wise-feed-forward, keras-pos-embd, keras-layer-normalization, keras-embed-sim, tika, keras-multi-head, keras-transformer, keras_bert, ktrain
Successfully installed keras-embed-sim-0.10.0 keras-layer-normalization-0.16.0 keras-multi-head-0.29.0 keras-pos-embd-0.13.0 keras-position-wise-feed-forward-0.8.0 keras-self-attention-0.51.0 keras-transformer-0.40.0 keras_bert-0.89.0 ktrain-0.41.4 langdetect-1.0.9 syntok-1.4.4 tika-2.6.0 whoosh-2.7.4
Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.17.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.11.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (71.0.4)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.64.1)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.17.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.26.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (13.9.2)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (0.0.8)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow) (0.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow) (3.0.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow) (3.0.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow) (0.1.2)
Requirement already satisfied: tf_keras in /usr/local/lib/python3.10/dist-packages (2.17.0)
Requirement already satisfied: tensorflow<2.18,>=2.17 in /usr/local/lib/python3.10/dist-packages (from tf_keras) (2.17.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (3.11.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (0.4.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (71.0.4)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (1.64.1)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (2.17.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (3.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (0.37.1)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.18,>=2.17->tf_keras) (1.26.4)

In [ ]:
import os
os.environ['TF_USE_LEGACY_KERAS']="1"

In [ ]:
import keras
import ktrain
from ktrain import text

# Dataset

In [ ]:
!gdown 1oIcFKdObxQnzAOEGQb02kPGeT_9bqtm2

Downloading...
From: https://drive.google.com/uc?id=1oIcFKdObxQnzAOEGQb02kPGeT_9bqtm2
To: /content/posts_train.csv
100% 1.32M/1.32M [00:00<00:00, 119MB/s]

In [ ]:
!gdown --id 114yGPdgJcrw0lpK1xrd1MdJbBohGP9TJ

/usr/local/lib/python3.10/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=114yGPdgJcrw0lpK1xrd1MdJbBohGP9TJ
To: /content/posts_test.csv
100% 567k/567k [00:00<00:00, 85.4MB/s]

In [ ]:
import pandas as pd

dataset = pd.read_csv('posts_train.csv')

In [ ]:
df_train = pd.read_csv('posts_train.csv')

In [ ]:
df_test = pd.read_csv('posts_test.csv')

In [ ]:
df_train

                                                   text     label
0     James DauntÂs taking it well. Abusing his sta...  negative
1     People who overcame panic and have decided to ...  negative
2     In 2019, the new presidents of Mexico and Arge...  negative
3     The German Chancellor nailed it with this line...  positive
4     New Jersey man faces multiple terror charges a...  negative
...                                                 ...       ...
2395  General drop in the #ElectricityMarkets prices...  negative
2396  @Nouriel How does America not go into a deflat...  negative
2397  @realDonaldTrump @WhiteHouse @POTUS @VP \r\r\n...  positive
2398  Good morning.\r\r\n\r\r\n Covid 19 is real ple...  positive
2399  To the healthcare workers, janitors, food work...  positive

[2400 rows x 2 columns]

In [ ]:
df_test

                                                   text     label
0     James DauntÂs taking it well. Abusing his sta...  negative
1     People who overcame panic and have decided to ...  negative
2     In 2019, the new presidents of Mexico and Arge...  negative
3     The German Chancellor nailed it with this line...  positive
4     New Jersey man faces multiple terror charges a...  negative
...                                                 ...       ...
2395  General drop in the #ElectricityMarkets prices...  negative
2396  @Nouriel How does America not go into a deflat...  negative
2397  @realDonaldTrump @WhiteHouse @POTUS @VP \r\r\n...  positive
2398  Good morning.\r\r\n\r\r\n Covid 19 is real ple...  positive
2399  To the healthcare workers, janitors, food work...  positive

[2400 rows x 2 columns]

# Ajuste Fino do BERT

In [ ]:
(x_train, y_train), (x_test, y_test), preproc = text.texts_from_df(df_train,
                                                                   'text', # coluna com dados textuais
                                                                   label_columns='label', # aqui pode ser multilabel
                                                                   maxlen=128,
                                                                   max_features=10000,
                                                                   preprocess_mode='bert',
                                                                   lang=None,
                                                                   val_df = df_test,
                                                                   random_state=42
                                                                   )

['negative', 'positive']
   negative  positive
0       1.0       0.0
1       1.0       0.0
2       1.0       0.0
3       0.0       1.0
4       1.0       0.0
['negative', 'positive']
   negative  positive
0       1.0       0.0
1       1.0       0.0
2       1.0       0.0
3       0.0       1.0
4       1.0       0.0
downloading pretrained BERT model (uncased_L-12_H-768_A-12.zip)...
[██████████████████████████████████████████████████]
extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: en

Is Multi-Label? False
preprocessing test...
language: en

In [ ]:
model = text.text_classifier('bert', (x_train, y_train) , preproc=preproc)
classifier = ktrain.get_learner(model,
                             train_data=(x_train, y_train),
                             val_data=(x_test, y_test),
                             batch_size=32
                             )

Is Multi-Label? False
maxlen is 128

/usr/local/lib/python3.10/dist-packages/tf_keras/src/initializers/initializers.py:121: UserWarning: The initializer GlorotNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initializer instance more than once.
  warnings.warn(

done.

In [ ]:
classifier.fit_onecycle(0.00001,10)

begin training using onecycle policy with max lr of 1e-05...
Epoch 1/10
75/75 [==============================] - 126s 1s/step - loss: 0.7254 - accuracy: 0.5383 - val_loss: 0.6464 - val_accuracy: 0.6554
Epoch 2/10
75/75 [==============================] - 104s 1s/step - loss: 0.5618 - accuracy: 0.7354 - val_loss: 0.3876 - val_accuracy: 0.8396
Epoch 3/10
75/75 [==============================] - 84s 1s/step - loss: 0.3058 - accuracy: 0.8754 - val_loss: 0.1686 - val_accuracy: 0.9392
Epoch 4/10
75/75 [==============================] - 103s 1s/step - loss: 0.1670 - accuracy: 0.9388 - val_loss: 0.0729 - val_accuracy: 0.9800
Epoch 5/10
75/75 [==============================] - 104s 1s/step - loss: 0.0737 - accuracy: 0.9779 - val_loss: 0.0262 - val_accuracy: 0.9962
Epoch 6/10
 6/75 [=>............................] - ETA: 56s - loss: 0.0445 - accuracy: 0.9896

KeyboardInterrupt:

In [ ]:
classifier.model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 Input-Token (InputLayer)    [(None, 128)]                0         []

 Input-Segment (InputLayer)  [(None, 128)]                0         []

 Embedding-Token (TokenEmbe  [(None, 128, 768),           2344089   ['Input-Token[0][0]']
 dding)                       (30522, 768)]               6

 Embedding-Segment (Embeddi  (None, 128, 768)             1536      ['Input-Segment[0][0]']
 ng)

 Embedding-Token-Segment (A  (None, 128, 768)             0         ['Embedding-Token[0][0]',
 dd)                                                                 'Embedding-Segment[0][0]']

 Embedding-Position (Positi  (None, 128, 768)             98304     ['Embedding-Token-Segment[0][0
 onEmbedding)                                                       ]']

 Embedding-Dropout (Dropout  (None, 128, 768)             0         ['Embedding-Position[0][0]']
 )

 Embedding-Norm (LayerNorma  (None, 128, 768)             1536      ['Embedding-Dropout[0][0]']
 lization)

 Encoder-1-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Embedding-Norm[0][0]']
 ention (MultiHeadAttention
 )

 Encoder-1-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-1-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-1-MultiHeadSelfAtt  (None, 128, 768)             0         ['Embedding-Norm[0][0]',
 ention-Add (Add)                                                    'Encoder-1-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-1-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-1-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-1-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-1-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-1-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-1-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-1-FeedForward-Add   (None, 128, 768)             0         ['Encoder-1-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-1-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-1-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-1-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-2-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Encoder-1-FeedForward-Norm[0
 ention (MultiHeadAttention                                         ][0]']
 )

 Encoder-2-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-2-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-2-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-1-FeedForward-Norm[0
 ention-Add (Add)                                                   ][0]',
                                                                     'Encoder-2-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-2-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-2-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-2-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-2-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-2-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-2-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-2-FeedForward-Add   (None, 128, 768)             0         ['Encoder-2-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-2-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-2-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-2-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-3-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Encoder-2-FeedForward-Norm[0
 ention (MultiHeadAttention                                         ][0]']
 )

 Encoder-3-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-3-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-3-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-2-FeedForward-Norm[0
 ention-Add (Add)                                                   ][0]',
                                                                     'Encoder-3-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-3-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-3-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-3-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-3-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-3-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-3-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-3-FeedForward-Add   (None, 128, 768)             0         ['Encoder-3-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-3-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-3-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-3-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-4-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Encoder-3-FeedForward-Norm[0
 ention (MultiHeadAttention                                         ][0]']
 )

 Encoder-4-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-4-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-4-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-3-FeedForward-Norm[0
 ention-Add (Add)                                                   ][0]',
                                                                     'Encoder-4-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-4-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-4-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-4-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-4-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-4-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-4-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-4-FeedForward-Add   (None, 128, 768)             0         ['Encoder-4-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-4-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-4-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-4-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-5-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Encoder-4-FeedForward-Norm[0
 ention (MultiHeadAttention                                         ][0]']
 )

 Encoder-5-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-5-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-5-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-4-FeedForward-Norm[0
 ention-Add (Add)                                                   ][0]',
                                                                     'Encoder-5-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-5-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-5-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-5-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-5-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-5-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-5-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-5-FeedForward-Add   (None, 128, 768)             0         ['Encoder-5-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-5-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-5-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-5-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-6-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Encoder-5-FeedForward-Norm[0
 ention (MultiHeadAttention                                         ][0]']
 )

 Encoder-6-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-6-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-6-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-5-FeedForward-Norm[0
 ention-Add (Add)                                                   ][0]',
                                                                     'Encoder-6-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-6-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-6-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-6-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-6-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-6-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-6-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-6-FeedForward-Add   (None, 128, 768)             0         ['Encoder-6-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-6-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-6-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-6-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-7-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Encoder-6-FeedForward-Norm[0
 ention (MultiHeadAttention                                         ][0]']
 )

 Encoder-7-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-7-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-7-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-6-FeedForward-Norm[0
 ention-Add (Add)                                                   ][0]',
                                                                     'Encoder-7-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-7-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-7-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-7-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-7-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-7-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-7-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-7-FeedForward-Add   (None, 128, 768)             0         ['Encoder-7-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-7-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-7-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-7-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-8-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Encoder-7-FeedForward-Norm[0
 ention (MultiHeadAttention                                         ][0]']
 )

 Encoder-8-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-8-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-8-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-7-FeedForward-Norm[0
 ention-Add (Add)                                                   ][0]',
                                                                     'Encoder-8-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-8-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-8-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-8-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-8-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-8-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-8-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-8-FeedForward-Add   (None, 128, 768)             0         ['Encoder-8-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-8-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-8-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-8-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-9-MultiHeadSelfAtt  (None, 128, 768)             2362368   ['Encoder-8-FeedForward-Norm[0
 ention (MultiHeadAttention                                         ][0]']
 )

 Encoder-9-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-9-MultiHeadSelfAtten
 ention-Dropout (Dropout)                                           tion[0][0]']

 Encoder-9-MultiHeadSelfAtt  (None, 128, 768)             0         ['Encoder-8-FeedForward-Norm[0
 ention-Add (Add)                                                   ][0]',
                                                                     'Encoder-9-MultiHeadSelfAtten
                                                                    tion-Dropout[0][0]']

 Encoder-9-MultiHeadSelfAtt  (None, 128, 768)             1536      ['Encoder-9-MultiHeadSelfAtten
 ention-Norm (LayerNormaliz                                         tion-Add[0][0]']
 ation)

 Encoder-9-FeedForward (Fee  (None, 128, 768)             4722432   ['Encoder-9-MultiHeadSelfAtten
 dForward)                                                          tion-Norm[0][0]']

 Encoder-9-FeedForward-Drop  (None, 128, 768)             0         ['Encoder-9-FeedForward[0][0]'
 out (Dropout)                                                      ]

 Encoder-9-FeedForward-Add   (None, 128, 768)             0         ['Encoder-9-MultiHeadSelfAtten
 (Add)                                                              tion-Norm[0][0]',
                                                                     'Encoder-9-FeedForward-Dropou
                                                                    t[0][0]']

 Encoder-9-FeedForward-Norm  (None, 128, 768)             1536      ['Encoder-9-FeedForward-Add[0]
  (LayerNormalization)                                              [0]']

 Encoder-10-MultiHeadSelfAt  (None, 128, 768)             2362368   ['Encoder-9-FeedForward-Norm[0
 tention (MultiHeadAttentio                                         ][0]']
 n)

 Encoder-10-MultiHeadSelfAt  (None, 128, 768)             0         ['Encoder-10-MultiHeadSelfAtte
 tention-Dropout (Dropout)                                          ntion[0][0]']

 Encoder-10-MultiHeadSelfAt  (None, 128, 768)             0         ['Encoder-9-FeedForward-Norm[0
 tention-Add (Add)                                                  ][0]',
                                                                     'Encoder-10-MultiHeadSelfAtte
                                                                    ntion-Dropout[0][0]']

 Encoder-10-MultiHeadSelfAt  (None, 128, 768)             1536      ['Encoder-10-MultiHeadSelfAtte
 tention-Norm (LayerNormali                                         ntion-Add[0][0]']
 zation)

 Encoder-10-FeedForward (Fe  (None, 128, 768)             4722432   ['Encoder-10-MultiHeadSelfAtte
 edForward)                                                         ntion-Norm[0][0]']

 Encoder-10-FeedForward-Dro  (None, 128, 768)             0         ['Encoder-10-FeedForward[0][0]
 pout (Dropout)                                                     ']

 Encoder-10-FeedForward-Add  (None, 128, 768)             0         ['Encoder-10-MultiHeadSelfAtte
  (Add)                                                             ntion-Norm[0][0]',
                                                                     'Encoder-10-FeedForward-Dropo
                                                                    ut[0][0]']

 Encoder-10-FeedForward-Nor  (None, 128, 768)             1536      ['Encoder-10-FeedForward-Add[0
 m (LayerNormalization)                                             ][0]']

 Encoder-11-MultiHeadSelfAt  (None, 128, 768)             2362368   ['Encoder-10-FeedForward-Norm[
 tention (MultiHeadAttentio                                         0][0]']
 n)

 Encoder-11-MultiHeadSelfAt  (None, 128, 768)             0         ['Encoder-11-MultiHeadSelfAtte
 tention-Dropout (Dropout)                                          ntion[0][0]']

 Encoder-11-MultiHeadSelfAt  (None, 128, 768)             0         ['Encoder-10-FeedForward-Norm[
 tention-Add (Add)                                                  0][0]',
                                                                     'Encoder-11-MultiHeadSelfAtte
                                                                    ntion-Dropout[0][0]']


In [ ]:
predictor = ktrain.get_predictor(classifier.model, preproc)

In [ ]:
df_test.text.to_list()

['James DauntÂ\x92s taking it well. Abusing his staff now for talking Â\x91utter shitÂ\x92 before threatening jobs, and then intimidating authors who Â\x91should know betterÂ\x92 than to speak out against Waterstones. \r\r\n\r\r\nhttps://t.co/zdCttC6rCu',
 'People who overcame panic and have decided to put their workforce so that ALL of us can have food and supplies of first need.\r\r\nIn this critical situation it is evident who are the ones who move the WORLD, the ENTREPRENEURS and THE Workers. (2) #Covid_19 #CoronavirusOutbreak',
 'In 2019, the new presidents of Mexico and Argentina announced plans to lift their struggling economies: ambitious oil projects that would boost state revenues. But COVID-19 has caused a severe price crash in the crude oil market \r\r\nhttps://t.co/EHXz7X48XM',
 'The German Chancellor nailed it with this line: "Those who sit at supermarket cash registers or restock shelves are doing one of the hardest jobs there is right now.Â\x94\r\r\nBe kind and show courtesy and respect #COVID19ON #COVID19 #COVIDCanada #COVID2019',
 'New Jersey man faces multiple terror charges after he allegedly coughed on a grocery store worker and then claimed to have the #coronavirus. https://t.co/z4TkoqDo92',
 'Just called mum and dad in UK (over 70). They are great but I offered help with online shopping etc. We might sometimes forget that this is not always easy.\r\r\n\r\r\nDo the same if you can. ??\r\r\nIf you are far from your parents like me Tech can be really useful. #COVID?19  #Coronavirus',
 'Those who ignore #coronavirus advisory should be dealt with strictly. Whether it is #RamNavami celebration in UP or #ShaheenaBagh in Delhi. You canÂ\x92t put lives of thousands of people in danger. #StaySafeStayHome',
 'While COVID-19 is making everyone stay at home these days, online shopping is becoming more important than ever. ThereÂ\x92s no better time to sit on your couch and join my #Magecart webinar ?? https://t.co/NNLN4hlrT9',
 'The is rough But we are fighting back Glad to partner with amp to get a ton of hand sanitizer in production Thanks Rob from the PA Distillers Guild More on this story to come',
 'Samsung estimated that profits had risen in the first quarter of the year, compared with the same period of 2019, thanks in part to the covid-19 outbreak. Although sales of its consumer gadgets may be hit along with the wider blow to the economy in 2020',
 'I have created a page on my website offering advice amp help to constituents on 19 The page includes health advice business amp employee advice local supermarket information education info amp useful contacts',
 'TERRIFYING VIDEO SHOWS A CVIRUS COUGH SPREAD ACROSS A SUPERMARKET\r\r\n\r\r\nScientists created a computer simulation to study how far the #coronavirus can travel indoors and found how a cloud of droplets will infect others after the sick person has walked away.\r\r\nhttps://t.co/A0oTjjsDdK',
 '@wierdduk @telegraaf Best to be precautionary.  A supermarket entry and visit can be treated as a place of potential COVID-19 contamination. Look at radiation protection and operating room practices for contamination control methods.  This is out of love ',
 'IÂ\x92m not saying itÂ\x92s your fault....but yÂ\x92all did ask for the Roaring 20s back and it came back full swing; pandemic, stock market crash, food and supply shortages, people losing their jobs, and bars closing. Just sayin #coronavirus',
 'So proud of these two They shaved their hair amp raised ovr  1k in 24 hours for our local food bank Basics Lanarkshire Foodbank are really struggling to meet local demand due to current crisis 19 but the biggest thank you is to all those who have kindly donated',
 'This special 90% off #DriveThruRPG bundle contains a dozen self-standing titles we have specially selected for people forced to self-isolate during the current crisis, including #comics, #fantasy fiction, #miniatures, and a #coloringbook!\r\r\n\r\r\nhttps://t.co/0d0QVIf1vP #DnD #RPG #TTRPG',
 '@callistoggawine You should be livid. Not only has he exposed you to Covid-19, he has exposed his buddies who will now expose more folk who will expose nurses, doctors, careworkers, refuse collectors, supermarket staff, delivery drivers, farmers etc. He i',
 "it's not good!\r\r\n\r\r\nCSPI Releases ConsumerÂ\x92s Guide to Restaurant Sick Leave Policies During COVID-19 Pandemic @CSPI https://t.co/qpnBiuSQkJ",
 'As an ex-journalist I know what it takes to cover a huge story + salute those on the media frontline.\r\r\nAs a consumer IÂ\x92m concerned about #Covid_19 coverage: itÂ\x92s relentlessly negative. So kudos to @theage for its Good News page. We need stories of hope. \r\r\nhttps://t.co/jGEQsVnNGN',
 '#China\'s #COVID2019 &amp; #ASF "outbreaks were almost certainly made far more severe by government-mandated restrictions on the disclosure of information to the public which inhibited efforts to combat diseases in their critical early stages" @JamestownTweets\r\r\nhttps://t.co/I6FrDsjrxy https://t.co/XU5YOTMt9z',
 'The vermin clearing supermarket shelves are selfish tw-ts! I donÂ\x92t care about myself, but I do care for my two year old daughters needs; formula &amp; nappies. Think of others you gob sh-tes! #covid19UK #coronavirus #COVID19',
 "Fake @asda voucher warning from @CTSI_U. Email claims to be from supermarket chain Asda and says you've received a voucher for money off shopping during the quarantine.\r\r\n\r\r\nForm to claim coupon actually steals credit card details. #ScamAlert #coronavirus",
 "Coronavirus: President's warning on hiking prices becomes real as four are arrested - https://t.co/crQKIO3gEH  #Coronavirus #museveni #traders #National #News https://t.co/vWSj2QmpM2",
 'and consumer are relaxing in lockdown while having some Quarantinis Our dynamic duo reviews life in during a 21st Century Apocalypse',
 'Check out AG Ferguson on warning about scams and also raising awareness',
 '@DamoPelham @vanOnselenP So clear that every supermarket is raided of food.\r\r\nSo clear that people hire buses to raid supermarkets in country towns and/or other suburbs.\r\r\nSo clear that everyone knows what to do.\r\r\nSo clear about mixed messaging.\r\r\n\r\r\nSo ',
 'It should be an extra fee for excessive purchasing at the supermarket. People wouldnÂ\x92t buy hell of toilet paper. #StayAtHome #Covid_19',
 'You truckers and myself as well a grocery store worker plus a few more are thank you for helping this world turn I bet people won t look at us as such low workers now I hope after this pandemic is over it changes the world for the better',
 'Fear and panic seems gripping in the UK . First time today, saw all food shelves and racks empty in both sainsbury and Tesco near me. This looks as real as approaching doomsday \r\r\n\r\r\n#coronavirus',
 'What EveryoneÂ\x92s Getting Wrong About the  #ToiletPaper Shortage https://t.co/6j8IiWkjTK\r\r\n#ToiletPaperPanic #coronavirus\r\r\n#StayAtHome #Covid_19 #covid19 #behaviour #confinement #consumer #Hoarding',
 'So BOJO refuses to use the word #lockdown &amp; so far as I can tell Â\x93helping a vulnerable person is okÂ\x94 then wee Krankie comes on &amp; says #lockdown DO NOT leave ur homes plus no food delivery slots for 3+ weeks so if the panic buyers stopped you getting food your f****d #coronavirus',
 "A sobering analysis on the state of oil. In short term prices should recover somewhat w/prod cuts coming. It's unlikely to be enough to cover the weak global demand caused by COVID-19. We'll be dealing w/ surplus supply for months | https://t.co/8KsjoIXAss https://t.co/52lnnvRB1E https://t.co/9kh5WT6YuN",
 'Although your business may be in a state not yet in lockdown, convincing customers itÂ\x92s safe to shop in your store is a retail challenge youÂ\x92ve likely never faced before. https://t.co/GluH0Wfxcd #coronavirus',
 'Scam Alert   Fraudsters are using supermarket branding to trick people in to thinking they are being offered money off purchases The email contains a link which aims to steal your personal and or financial details More info at',
 'As stores around the nation are struggling to keep up with the demand for food, toilet paper and hand sanitizer, there is another golden commodity fast disappearing from the shelves amid the #coronavirus crisis: firearms. https://t.co/W2gIWeJMTW',
 'Please send me or pictures with names of people you think are heroes Can be anyone from nurses doctors supermarket staff police officers health care workers etc info@boxtonesband com',
 "With COVID-19, there are so many aspects of life that can no longer be taken for granted: a stable income, full supermarket shelves, the freedom to go to church every Sunday.\r\r\n\r\r\nThat's what I'm blogging about this week. https://t.co/fri3wEdj6D",
 'A man in New Jersey was #Charged with terroristic threats and various other crimes on Tuesday after allegedly coughing on a supermarket employee, telling her he had contracted the novel #Coronavirus (COVID-19), and insulting her and other ...\r\r\n \r\r\nhttps://t.co/LAE6ahgPdm https://t.co/6Mix0Qyxz6',
 'The current approach by the big three food retailers is not fit for purpose exposed by the literal failure of the retailers to deliver during the loading too much pressure on which itself needs to expand to future demand',
 'Can all these reports be wrong?\r\r\nThe economic outlook for Americans just plummeted the most since the financial crisis as #coronavirus threatens deep recession...\r\r\nhttps://t.co/5M6giqOA2G\r\r\n#QAnon ?? ?',
 'Thank you to all our carers, front line hospital workers, delivery drivers, supermarket staff, community volunteers &amp; all the other amazing people that are going above &amp; beyond during this surreal time ?\r\r\n\r\r\n#stayhome #StayHomeSaveLives #nhsstaff #clapforthenhs #clapforourcarers https://t.co/I51JeDQdt5',
 "We've hit 200+ registrations - don't miss out on today's FREE webinar where Earle Hall will discuss how business and consumer behavior will change following COVID-19. Secure your spot now:Â\xa0https://t.co/rvjWVSbD2G https://t.co/vCLaiQh2qv",
 '@DoctorYasmin Would you let a grocery store manager take care of children right now? Only 800-900 customers daily. Expectations are three meals per day, two days a week on their days off. Asking for a friend. #COVID19 #Covid_19 #GeneralStrike #',
 'Even as South Dakota ethanol producers struggle with low prices during the COVID-19 pandemic, developers of the long-disputed Keystone XL Pipeline are getting set to build their $8 billion project that will transport Canadian oil across the state onÂ\x85 https://t.co/zOUUfFtFSH',
 'If we contemplate this pendemic, people will not die of #Coronavirus but die of fear/panic, no money to get drugs, food &amp;other complications.\r\r\nOur brother lender, China is battling seriously of #COVID19. No serious measure from FG. Setting up committee cannot cut it\r\r\n#nysc',
 'I get washing down your groceries, I really do. Everything is scary as fuck.\r\r\n\r\r\nBut the real danger is the people youÂ\x92re standing next to at the grocery store.\r\r\n\r\r\nAnd the egregious lack of Medicare for all in this shithole country.\r\r\n#Covid_19',
 'Amidst the #COVID19 pandemic, @CarOffer_ has launched its Consumer Buying feature for free and ahead of schedule. It should help auto dealers drive sales and traffic during this time. https://t.co/0sDLwcexQE',
 'To all the doctors, nurses, hospital workers, EMS people, grocery, factory and drug store workers. On behalf of us all thank you for all being heroes. The rest of us, be heroes too by doing your part. #Heroes #coronavirus #ThankYou https://t.co/YyaWElwrZI',
 'On the 5th day of SAH my true love gave to me 5 MINUTES ALONE, 4 home school websites, 3 stock market lectures, 2 bags of canned food, and hopefully not COVID-19.',
 'Important quote from Dr. Birx yesterday: Â\x93The next 2 weeks are extraordinarily important. This is the moment to not be going to the grocery store, not going to the pharmacy, but doing everything you can to keep your family and your friends safe...Â\x94 #CoronavirusOutbreak #Covid_19',
 "everyone drop a food u panic bought bc of covid-19. I'll start: riced cauliflower",
 'Make sure your neighbors have hand sanitizer. If the shelves are bare in your neighborhood and up town, expect your coronavirus cases to jump. https://t.co/miIj2pqKtO\r\r\n#Coronavirus #Covid_19 #WorldHealthDay',
 'Not gonna happen but would be nice if pro sports owners realized theyÂ\x92re leagues are pretty much worth zero without fans in the stands and lower ticket and concession prices when things get back to normal. #coronavirus',
 'Times are tough and scary for most of us.  But tweets and posts like Â\x93Home due to #CoronaVirus? Now is an ideal time for online shopping. Â\x93 are a complete turn off to me.',
 'I knew it was going to be bad...but not this bad https://t.co/IaACfFlNAx',
 'ATIKU This morning my local grocery store the fresh produce man whose been serving our neighborhood for over a decade was devastated His wife called him in tears their families in Italy are crying living in fear amp they lost 10 more doctors to 19 Italy has been destroyed',
 "I will unfollow n block everyone even if i get zero followers who is boasting about food in their house and About what and how much they have stocked, I have come across many families around here who don't even have 5 kg rice stock... ?? #coronavirus Grocery Panic Buying",
 'Hand sanitizer and masks available in Harare and Bulawayo!\r\r\n\r\r\nPlease be safe , and keep your loved ones safe as well.  Get your sanitizer now!\r\r\n\r\r\n#coronavirusZim #Zimbabwe  #COVID2019 \r\r\n#21daysLockdown #COVID19 #coronavirus https://t.co/WDQD6zvvOg',
 'We are excited to announce the launch of our new produced in partnership with global The study is focused on perceptions of and retailers during the pandemic New results will be posted weekly Read more at',
 'WeÂ\x92re experiencing the fuel worldÂ\x92s version of Â\x91#ThrowbackThursdayÂ\x92. Due to COVID-19 and the geopolitical turmoil between OPEC/Russia, crude oil is near a 17-year low.\r\r\n\r\r\n@CrystalFlashMI can help you lock in fuel prices at levels not seen since 2003.\r\r\nhttps://t.co/P2eHVPsjgz',
 'i hope everyone is feeling well! itÂ\x92s so important right now to self quarantine to ensure we arenÂ\x92t endangering ourselves or anyone who canÂ\x92t handle this virus ?',
 'From 3pm with @oliverpeterson:\r\r\n\r\r\nÂ\x95 Coronavirus latest, three health care workers have tested positive to COVID-19 in WA.\r\r\nÂ\x95 Consumer Protection taking your calls.\r\r\nÂ\x95 Will the NBN network cope with more and more Aussies working from home? https://t.co/SDXzJ5zVgf',
 '.@moscowtimes reports that food prices in #Russia rose in March. This occurred following panic buying resultant from the #coronavirus #pandemic and the crash of the Ruble: https://t.co/BBpVoTfZYp',
 'wifi and streaming services should lower their prices to make it affordable for everyone or make a 3 months free deal so that people can be encouraged to be quarantined and stay inside and not be bored #coronavirus',
 "'I'm going to keep working': Grocery clerks unlikely heroes in U.S....For Philip, a grocery store clerk, itÂ\x92s not a matter of if he gets #coronavirus, but when. Like many Americans. https://t.co/w9sQFfyPn0",
 '@mlq3 Then let the hospitals take a four day holiday.\r\r\n\r\r\nYou die faster from lack of food than from covid-19. There is no acceptable excuse for pulling anyone offline when the supply structure is already stressed. As long as there is demand, they should',
 '"The next crisis we are facing is the seasonal workers" \r\r\nhttps://t.co/woJgZO5Bsz https://t.co/2s1AlJdwDD',
 '@eBay_UK how are you allowing people to sell a single sheet of paper, ACTUALLY USED FFS. Prices for a pack of toilet paper are ridiculous ???  #coronavirus #COVID2019 #Armageddon https://t.co/CwzmRmjSj5',
 'Yesterday we took around 50 calls for help with prescriptions &amp; shopping &amp; dozens of requests via our online form. Here are 2 of our lovely volunteers in action!\r\r\n#thecourieruk #coronavirus #coronavirusuk #COVID19 #kinross #covid19UK #Selfisolationhelp #communitysupport https://t.co/gyu1MQh3m6',
 'Left the house at 7:45 to go to the store to stock up to get some food and essentials. Clearly everyone in Long Island had the same idea. I got the last 2 cases of 40 pack water and the death stares I got were terrifying. Had to hurry up and come out. #Covid_19',
 'cannot protect employees but keep virus from spreading Some shoppers don t wear masks Make them all wear masks or face coverings RT Grocery workers are beginning to die of 19',
 "Guys I'm going crazy I'm so tired of being home I can't go do anything ? ,I can't even go to work, and I can't go online shopping cause I have no job anymore / no money! \r\r\n#CoronaVirusUpdate #coronavirus",
 '@lou_nautic Yesterday, I took 2 steps towards the attendant at the supermarket self checkout line to ask a question and her eyes got big like saucers as she retreated as if I was some rabid bear charging. So, yeah...that was my COVID-19 era faux pas...?',
 '#Covid-19 Is Bad for the #Automotive IndustryÂ\x97and Even Worse for EVs Factory shutdowns signal a troubled road ahead for #carmakers, while low gas prices could hit electric #vehicles hard. https://t.co/lA0ZEdDvS5',
 '@rrrins Hi Rina! Have some news from a client I think might be a fit for your Well To Do newsletter (consumer wellness during COVID-19) -- would you be willing to share your email so I can send it your way? Appreciate the consideration!',
 'Â\x93We are keeping an eye on things and Boomplay Music? will do what it can to support and help people get through this." https://t.co/cDKeWr32F2 #Boomplay #COVID19',
 'The point is ONLY TRAVEL IF YOU ARE KEY WORKER If your job not vital to everyday living fighting ie you re not a health social care worker refuse collector supermarket delivery driver police officer etc STAY HOME My entire company is WFH since last Tuesday',
 "Supermarket 10 also pointless.\r\r\n11 and 12 imminent.\r\r\nAnd then I'm done.\r\r\nNice to know this city is full of great people.\r\r\n#COVID19 \r\r\n#coronavirus\r\r\n#StopHoarding \r\r\n#panicbuyinguk #London",
 '@CTVNews Pre-COVID-19, Chicken wholesaled @ $3.50/kg. After the Â\x93HoardersÂ\x94 filled their freezers, chicken sells @ $1.00/kg. LOBLAWS is asking suppliers to store tones of chicken, but wonÂ\x92t reduce prices.@brianrmitchell4 @torontobaghead @alan_poirier @g',
 'Despite how serious the headline sounds the baby chick video in this story is pretty cute',
 '@WHO @realDonaldTrump @GovernmentRF @NCDCgov @PDChina @UN So there is no cure for a virus that can be killed by sanitizer and soap?? #covid19 #coronavirus #covid-19',
 '#coronavirus has got its hooks into #Tesco Extra, Watford. But why are they breaking up the multipack products and selling the individual contents at vastly inflated prices? IsnÂ\x92t that illegal? https://t.co/4eb18KaVvl',
 "@mccrory @Costco MyPOV: pretty much. well it's for the whole house and extended family. so i guess we may be okay. \r\r\n\r\r\nwe ran the calculator and given the folks here it could be about 31 to 60 days\r\r\n\r\r\n#shelterinplace #coronavirus #covid19 #coronapocal",
 "Consumer Reports tested Facebook Ads' claim they would reject ads spreading COVID-19 misinformation. https://t.co/FVRWWd7Gzh via @SusanEDub, @sejournal",
 'It seems smart for one of the large streaming services to slash prices in half for ~3 months. Tagline: Save lives...stay in and binge. This is weirdly a perfect time for streaming services to step up and help communicate #socialdistancing.\r\r\n\r\r\n#covid19 #coronavirus #flattenthecurve',
 'H.E. Mr. Ali bin Ahmed Al-Kuwari, Minister of Commerce and Industry, toured a number of hypermarkets to inspect, assess and monitor markets, and ensure the availability of food and consumer goods at stable prices. #Qatar #YourSafetyIsMySafety https://t.co/IiDtfp8LHr',

In [ ]:
y_pred = predictor.predict(df_test.text.to_list())
y_pred

['negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'negative',
 'negative',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'positive',
 'positive',
 'positive',
 'negative',
 'negative',
 'positive',
 'negative',
 'positive',
 'negative',
 'negative',
 'positive',
 'positive',
 ...]

In [ ]:
predictor.predict(['General drop in the #ElectricityMarkets prices...	'])

['negative']

In [ ]:
from sklearn.metrics import classification_report


y_true = df_test.label.to_list()
y_true

print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

    negative       0.97      1.00      0.98      1168
    positive       1.00      0.97      0.98      1232

    accuracy                           0.98      2400
   macro avg       0.98      0.98      0.98      2400
weighted avg       0.98      0.98      0.98      2400